# Workflow that publishes the package to PyPi
name: Publish PyPi Package

# Trigger manually
on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1.4.1
      - name: Install dependencies
        run: poetry install

      - name: Build package
        run: poetry build

      - name: Publish package
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: poetry publish --username $TWINE_USERNAME --password $TWINE_PASSWORD
